version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.1

workflows:
  lint_pack_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          name: pack-npm
          source-dir: src/npm
          destination-orb-path: packed/npm/orb.yml
          workspace-path: packed/npm/orb.yml
          artifact-path: packed/npm/orb.yml
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          name: publish-dev-npm
          orb-name: sugarshin/npm
          orb-path: workspace/packed/npm/orb.yml
          requires:
            - pack-npm
      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-workflow-npm
          ssh-fingerprints: 84:ce:ef:5a:1a:c2:65:df:54:80:ad:80:d7:7f:50:47
          requires:
            - publish-dev-npm
      - orb-tools/dev-promote-prod:
          name: dev-promote-prod-npm
          orb-name: sugarshin/npm
          release: patch # TODO
          ssh-fingerprints: 84:ce:ef:5a:1a:c2:65:df:54:80:ad:80:d7:7f:50:47
          requires:
            - trigger-integration-workflow-npm
          filters:
            branches:
              only: master
